### PR TITLE
switch block-pvc-scanner to psutil

### PR DESCRIPTION
**Pull request by balihb**
https://github.com/giampaolo/psutil

benefits:
- this is a more idiomatic python solution.
- shorter code
- less resource usage, since it won't spawn two shell commands in the background
- more reliable, as it is not using as much magical splits
- still used regex objects are pre compiled for even less resource usage

### CODE REVIEW

**Comment by balihb** [comment]
also I've tested the current solution and my solution and the current one is not working on the environment I've tested it on (this one does)

**Comment by kais271** [comment]
@balihb Hi sir, thank you for your provide this solution. I will  read that seriously later. Beacause I'm so busy with work recently

**Comment by kais271** [comment]
> also I've tested the current solution and my solution and the current one is not working on the environment I've tested it on (this one does)


@balihb Hi , could you please tell me that the fialed env info ?  I want to know why. And I have learned about psutil, Its compatibility and functions are very strong. For this block-pvc-scanner just one function, so I don't want to add other packages  if the  built-in package can work easy and normally.

**Comment by kais271** [comment]
Close merge . You can continue to optimize this solution.

**Comment by balihb** [comment]
I've made some bigger changes:
https://github.com/balihb/pvc-exporter/tree/omaster
feel free to port any of it.

**Pull request closed without merging**
